spring.application.name=week15-day02-backend
<<<<<<< HEAD
=======

# Database тохиргоо
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console идэвжүүлэх
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA тохиргоо
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 6e4e8e061b6715b7d794d8ecfcc589ae4a8bd6fd
